name = "simple-antiques"
compatibility_date = "2025-10-11"
pages_build_output_dir = "./public"

[observability]
enabled = true

[[d1_databases]]
binding = "gallery_db"
database_name = "ej-antiques"
database_id = "0fe8ddbd-6707-4717-bed6-971f1f79ef69"
